=== LouisDanh/WebProgramming/src/main/webapp/WEB-INF/dtd/tiles-config_2_0.dtd
<!ENTITY % TilesAttrs "
    name        CDATA    #REQUIRED
    value       CDATA    #IMPLIED
    type        CDATA    #IMPLIED
    cascade     (true | false) #IMPLIED
    role        CDATA    #IMPLIED
    expr        CDATA    #IMPLIED
    inherit     (true | false) #IMPLIED
">
<!ELEMENT tiles-definitions (definition*)>
<!ELEMENT definition (put-attribute*, put-list-attribute*, set-property*)>
<!ATTLIST definition
    name        CDATA    #REQUIRED
    template    CDATA    #IMPLIED
    role        CDATA    #IMPLIED
>
<!ELEMENT put-attribute EMPTY>
<!ATTLIST put-attribute %TilesAttrs;>
<!ELEMENT put-list-attribute (add-attribute*)>
<!ATTLIST put-list-attribute
    name        CDATA    #REQUIRED
>
<!ELEMENT add-attribute EMPTY>
<!ATTLIST add-attribute %TilesAttrs;>
<!ELEMENT set-property EMPTY>
<!ATTLIST set-property
    name        CDATA    #REQUIRED
    value       CDATA    #REQUIRED
>

=== LouisDanh/WebProgramming/src/main/webapp/WEB-INF/tiles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tiles-definitions PUBLIC 
    "-//Apache Software Foundation//DTD Tiles Configuration 2.0//EN" 
    "dtd/tiles-config_2_0.dtd">
<tiles-definitions>
	<!-- Định nghĩa layout chung cho tất cả các trang -->
	<definition name="baseLayout"
		template="/views/shares/layout.jsp">
		<put-attribute name="header"
			value="/views/shares/header.jsp" />
		<put-attribute name="footer"
			value="/views/shares/footer.jsp" />
		<put-attribute name="body" value="" />
		<put-list-attribute name="pageCss"  />
		<put-list-attribute name="pageJs"  />
		<put-list-attribute name="pageAjax"/>
	</definition>
</tiles-definitions>
